//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
set up:
start/stop button on digital port 1
this is for code is set up for 2 motor drive left motor attached connected to port 3 and right to port 2
this code CAN be change to beter suit your needs

How to use:
put commands and function calls after "put code here"
function is just a a bunch of commands you can "call" with a single line 
in some functions you can edit things like in "turnRight()" by chaning the varables in the () example "turnRight(30, 10);" would turn right at speed of 30 for 10 seconds
after eash command dont forget to put ";"
to compair two things in a if(){} use "==" for equal ">" greater then "<" less than and ">=" for greater then or equal to 

Notes:
This program has a built in E stop start/stop button on digi port 1 MUST be in port one and pressed for anything to happen 

Trouble Shooting:
robot doesn't go straight
	check if both motors are plugged in
		yes: try only using the "goForward(125, 5);", did it curve?
			yes:In the motor and sensor set up revers the offending motor if that doesnt work ask for help
				
			
			no: Ask for help
		
		no: plug it into Vexcoretex

built in functions:

turnRight(speed,how long);
 turns the robot right
 speed how fast to turn accepts vaules from -120 to 120
 how long to turn in seconds
 
turnLeft(spped, how long);
 turns the robot left
 speed how fast to turn accepts vaules from -120 to 120
 how long to turn in seconds
 
goForward(speed, time);
 turns both drive motors
 speed how fast to go accepts vaules from -125 to 125
 time how long to run in seconds 
 
 creits:
 writer:keith Nguyen
 QA testing: Macy, Dainel
*/

void turnRight(speed, time){
 startMotor(port2, speed);
 startMotor(port3, speed - 5);
 wait(howLong);
 stopMotor(port2);
 stopMotor(port3);
}

void turnRight(speed,time){
 startMotor(port2, speed -5 );
 startMotor(port3, speed);
 wait(time);
 stopMotor(port2);
 stopMotor(port3);
}

void goforward(speed, time){
 startMotor(port2, speed);
 startMotor(port3, speed);
 wait(time);
 stopMotor(port2);
 stopMotor(port3);
}

boolean running = false
task main(){            
 if(1==1){//start a loop 
	 if(running == true){//runs only if running is true
		 //PUT CODE HERE
		 
		 
		 
		 
		 
		 
		 
		 
	 }
	 else{ //this code runs if running doesn't == true
		stopMotor(port2);//stops right motor
		stopMotor(port3);//stops left motor
	 }
	 if(Ebutton == 1){//if Ebutton is pressed this runs 
		 running = runing!;//toggels running from false to true and vis versa 
	 }
 }
}